### PR TITLE
updated for swift1.2/xcode 6.3.2

### PR DESCRIPTION
**Pull request by fernandomorgan**
updated calls to dispatch_apply (added a closure parameter) and changed Uint to Int in the CGxx functions

### CODE REVIEW

**Comment by saniul** [comment]
Thanks!

**Comment by saniul** [comment]
@fernandomorgan May I ask what you’re using Mendel for?

**Comment by fernandomorgan** [comment]
Right now, I only started looking at the code :). But I did some work with a simple GA some years ago. I was trying to explore GAs to create strategies for computer players in strategy games (there was a really interesting article on that in one of the first GameDev articles), but I ended up using my algorithm in a SQL tuning product  

I got inspiration from Don O'Brien

http://aaalab.stanford.edu/about-us/don-obrien/

and the original article is here (in text format) - but readable

https://archive.org/stream/GDM_FebMar_1996/GDM_FebMar_1996_djvu.txt

Don's page (with a windows binary for Cloak,Dagger and DNA):
http://www.supermaze.com

**Comment by saniul** [comment]
:+1: Thanks!

**Pull request merged**
